const REFRESH_WORLD_STATE = 'REFRESH_WORLD_STATE'
export { REFRESH_WORLD_STATE }

const SET_WORLD_STATE = 'SET_WORLD_STATE'
export { SET_WORLD_STATE }

const SET_ALERTS = 'SET_ALERTS'
export { SET_ALERTS }

const SET_INVASIONS = 'SET_INVASIONS'
export { SET_INVASIONS }
